version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - '.:/app'
  elasticstack:
    build:
      context: elk
      dockerfile: Dockerfile
    container_name: elasticstack
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"



volumes:
  elasticdata:
    driver: local